http {
   # Настройка upstream для балансировки нагрузки
   upstream backend_servers {
       server backend1.example.com;
       server backend2.example.com;
       server backend3.example.com;
   }
   
   limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/m;

   server {
       listen 80;
       # Делаем ограничение для ВСЕХ запросов (а не конкретному блоку)
       limit_req zone=mylimit burst=0 nodelay;
       error_page 429 = /custom_429.html;

       location / {
           proxy_pass http://backend_servers;
       }

       location = /custom_429.html {
            return 429 'Too Many Requests - Rate limit exceeded.\n';
        }

   }
}
 
# burst=0 — не допускает всплесков запросов, строго 1 в 6 секунд.
# nodelay — без задержек, сразу отклоняет лишние запросы.